name: Deploy to IPFS via Pinata

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to IPFS
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.4
        with:
          path: './website-td2'
          pin-name: 'Website to deploy'
          pinata-api-key: df427a1f1ba8016585de
          pinata-secret-api-key: bfdc8f190ffd7d4faf51377c82bc5062848d8c3c78b6d4434c06763071923fd1
          remove-old: false
          verbose: true
